name: Push docker image
on: [push]
jobs:
  Push-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Log in to Docker Hub
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: ğŸ³ Build and publish docker image to docker hub
        run: | 
          docker build -t weblwabl/nginx_wp:latest .
          docker push weblwabl/nginx_wp:latest
      - run: echo "This job's status is ${{ job.status }}."